services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./build/app/Dockerfile
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_DATABASE: ticket_dev
  #     MYSQL_USERNAME: root
  #     MYSQL_PASSWORD: randomrootpassword
  #   command: sh -c "npm install && npm run dev"
  #   expose:
  #     - "3000"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  mysql:
    build:
      context: .
      dockerfile: ./build/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ticket_dev
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: randomrootpassword
    expose:
      - "3306"
    ports:
      - "3306:3306"