services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ticket_dev
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: randomrootpassword
    expose:
      - "3306"
    ports:
      - "3306:3306"